"""English AI text pattern rules.

This module defines cliché phrases, structural patterns, and stylistic
markers commonly found in AI-generated English text. Each rule has a
category, severity, and optional replacement suggestion.
"""

from typing import Dict, List, Tuple


# ---------------------------------------------------------------------------
# Cliché AI phrases -- exact or near-exact string matches
# ---------------------------------------------------------------------------

CLICHE_PHRASES: List[Tuple[str, str, str, str]] = [
    # (pattern, category, severity, replacement)
    ("In today's rapidly evolving", "cliche_opening", "error",
     "Start directly with the topic"),
    ("In today's fast-paced", "cliche_opening", "error",
     "Start directly with the topic"),
    ("In today's ever-changing", "cliche_opening", "error",
     "Start directly with the topic"),
    ("In an increasingly digital world", "cliche_opening", "error",
     "Start directly with the topic"),
    ("In the rapidly evolving landscape of", "cliche_opening", "error",
     "Start directly with the topic"),
    ("It's important to note", "filler_hedge", "warning",
     "Delete or state the point directly"),
    ("It is important to note", "filler_hedge", "warning",
     "Delete or state the point directly"),
    ("It is worth noting that", "filler_hedge", "warning",
     "Delete or state the point directly"),
    ("It should be noted that", "filler_hedge", "warning",
     "Delete or state the point directly"),
    ("It goes without saying", "filler_hedge", "warning",
     "Delete entirely"),
    ("Needless to say", "filler_hedge", "warning",
     "Delete entirely"),
    ("delve into", "overused_word", "error",
     "explore / examine / look at"),
    ("delve deeper into", "overused_word", "error",
     "explore / examine / investigate"),
    ("landscape", "overused_word", "warning",
     "field / area / sector / market"),
    ("leverage", "overused_word", "error",
     "use / build on / take advantage of"),
    ("streamline", "overused_word", "warning",
     "simplify / speed up / improve"),
    ("robust", "overused_word", "warning",
     "strong / reliable / solid"),
    ("comprehensive", "overused_word", "info",
     "full / complete / thorough"),
    ("cutting-edge", "booster_word", "warning",
     "advanced / latest / modern"),
    ("game-changing", "booster_word", "error",
     "significant / major / important"),
    ("revolutionize", "booster_word", "error",
     "transform / change / improve"),
    ("paradigm shift", "booster_word", "error",
     "fundamental change / major shift"),
    ("transformative", "booster_word", "warning",
     "significant / impactful / major"),
    ("innovative", "booster_word", "info",
     "new / novel / creative"),
    ("groundbreaking", "booster_word", "error",
     "important / new / notable"),
    ("state-of-the-art", "booster_word", "warning",
     "latest / current / modern"),
    ("seamless", "booster_word", "warning",
     "smooth / easy / integrated"),
    ("seamlessly", "booster_word", "warning",
     "smoothly / easily"),
    ("unleash", "booster_word", "error",
     "release / enable / unlock"),
    ("unlock", "overused_word", "info",
     "open / enable / access"),
    ("empower", "overused_word", "warning",
     "enable / support / help"),
    ("empowers", "overused_word", "warning",
     "enables / supports / helps"),
    ("foster", "overused_word", "warning",
     "encourage / promote / support"),
    ("facilitate", "overused_word", "warning",
     "enable / help / allow"),
    ("facilitates", "overused_word", "warning",
     "enables / helps / allows"),
    ("utilize", "overused_word", "warning",
     "use"),
    ("utilizing", "overused_word", "warning",
     "using"),
    ("implement", "overused_word", "info",
     "do / carry out / put in place"),
    ("implementing", "overused_word", "info",
     "putting in place / rolling out"),
    ("tailored", "overused_word", "info",
     "custom / specific / adapted"),
    ("bespoke", "overused_word", "info",
     "custom / made-to-order"),
    ("holistic", "overused_word", "warning",
     "complete / overall / full"),
    ("holistically", "overused_word", "warning",
     "completely / as a whole"),
    ("multifaceted", "overused_word", "warning",
     "complex / varied / many-sided"),
    ("nuanced", "overused_word", "info",
     "detailed / subtle / specific"),
    ("pivotal", "booster_word", "warning",
     "important / key / central"),
    ("crucial", "booster_word", "info",
     "important / key"),
    ("essential", "booster_word", "info",
     "necessary / needed / key"),
    ("paramount", "booster_word", "warning",
     "most important / top priority"),
    ("imperative", "booster_word", "warning",
     "necessary / vital / required"),
    ("vital", "booster_word", "info",
     "important / necessary"),
    ("notably", "filler_hedge", "info",
     "especially / particularly"),
    ("interestingly", "filler_hedge", "info",
     "Delete or rephrase"),
    ("arguably", "filler_hedge", "info",
     "Delete or state directly"),
    ("furthermore", "transition_word", "info",
     "Also / And / Plus"),
    ("moreover", "transition_word", "info",
     "Also / And / Plus"),
    ("additionally", "transition_word", "info",
     "Also / And"),
    ("consequently", "transition_word", "info",
     "So / As a result"),
    ("nevertheless", "transition_word", "info",
     "But / Still / Even so"),
    ("nonetheless", "transition_word", "info",
     "But / Still / Even so"),
    ("henceforth", "transition_word", "warning",
     "From now on"),
    ("hereby", "transition_word", "warning",
     "Delete -- usually unnecessary"),
    ("a myriad of", "wordiness", "info",
     "many / countless"),
    ("in order to", "wordiness", "info",
     "to"),
    ("in an effort to", "wordiness", "warning",
     "to"),
    ("for the purpose of", "wordiness", "warning",
     "to"),
    ("with regard to", "wordiness", "info",
     "about / regarding"),
    ("in light of", "wordiness", "info",
     "because / given"),
    ("at the end of the day", "cliche_closing", "error",
     "Delete or state conclusion directly"),
    ("in conclusion", "cliche_closing", "warning",
     "Delete -- let the conclusion speak"),
    ("to summarize", "cliche_closing", "info",
     "Delete -- let the conclusion speak"),
    ("in summary", "cliche_closing", "info",
     "Delete -- let the conclusion speak"),
    ("wrapping up", "cliche_closing", "info",
     "Delete -- let the conclusion speak"),
    ("as we look ahead", "cliche_closing", "warning",
     "Delete or state next steps directly"),
    ("looking to the future", "cliche_closing", "warning",
     "Delete or state next steps directly"),
    ("the journey ahead", "cliche_closing", "error",
     "Delete"),
    ("embark on a journey", "cliche_metaphor", "error",
     "start / begin"),
    ("navigate the complexities", "cliche_metaphor", "error",
     "handle / deal with / address"),
    ("shed light on", "cliche_metaphor", "warning",
     "explain / clarify / reveal"),
    ("bridge the gap", "cliche_metaphor", "warning",
     "connect / link"),
    ("drive growth", "cliche_metaphor", "warning",
     "grow / increase / expand"),
    ("drive innovation", "cliche_metaphor", "warning",
     "create / develop / advance"),
    ("elevate", "overused_word", "info",
     "improve / raise / enhance"),
    ("elevating", "overused_word", "info",
     "improving / raising"),
    ("stakeholders", "overused_word", "info",
     "people involved / team / partners"),
    ("synergy", "overused_word", "error",
     "collaboration / teamwork / combined effort"),
    ("synergies", "overused_word", "error",
     "collaborations / combined benefits"),
    ("best practices", "overused_word", "info",
     "effective methods / proven approaches"),
    ("thought leader", "overused_word", "warning",
     "expert / authority / specialist"),
    ("thought leadership", "overused_word", "warning",
     "expertise / authority"),
    ("ecosystem", "overused_word", "warning",
     "network / system / community"),
    ("ecosystems", "overused_word", "warning",
     "networks / systems / communities"),
    ("tapestry", "cliche_metaphor", "error",
     "mix / collection / variety"),
    ("rich tapestry", "cliche_metaphor", "error",
     "variety / diversity / range"),
    ("testament to", "cliche_metaphor", "warning",
     "shows / proves / demonstrates"),
    ("beacon of", "cliche_metaphor", "error",
     "example of / sign of"),
    ("catalyst for", "cliche_metaphor", "warning",
     "cause of / spark for / trigger for"),
    ("undeniably", "booster_word", "warning",
     "clearly / certainly"),
    ("unquestionably", "booster_word", "warning",
     "clearly / certainly"),
    ("undeniable", "booster_word", "warning",
     "clear / certain"),
    ("unprecedented", "booster_word", "warning",
     "rare / unusual / never-before-seen"),
    ("unprecedented times", "booster_word", "error",
     "Delete -- overused since 2020"),
    ("in these unprecedented times", "booster_word", "error",
     "Delete entirely"),
    ("in the realm of", "wordiness", "warning",
     "in / within"),
    ("on the other hand", "transition_word", "info",
     "But / However"),
    ("on the flip side", "transition_word", "info",
     "But / However"),
    ("it is evident that", "filler_hedge", "warning",
     "Delete -- state the evidence directly"),
    ("it is clear that", "filler_hedge", "warning",
     "Delete -- state the point directly"),
    ("it is crucial to", "filler_hedge", "warning",
     "Delete -- state the action directly"),
    ("it is essential to", "filler_hedge", "warning",
     "Delete -- state the action directly"),
    ("it cannot be overstated", "filler_hedge", "error",
     "Delete entirely"),
    ("serves as a", "wordiness", "info",
     "is / acts as"),
    ("plays a pivotal role", "wordiness", "warning",
     "is important / matters"),
    ("plays a crucial role", "wordiness", "warning",
     "is important / matters"),
    ("plays a key role", "wordiness", "info",
     "is important / matters"),
    ("plays an important role", "wordiness", "info",
     "is important / matters"),
    ("make informed decisions", "cliche_phrase", "info",
     "make good decisions / decide wisely"),
    ("at its core", "filler_hedge", "info",
     "Delete or simplify"),
    ("at the heart of", "filler_hedge", "info",
     "in / at the center of"),
    ("at the forefront", "filler_hedge", "info",
     "leading / ahead"),
    ("pushing the boundaries", "cliche_metaphor", "warning",
     "advancing / expanding limits"),
    ("pushing the envelope", "cliche_metaphor", "warning",
     "advancing / going further"),
    ("breaking new ground", "cliche_metaphor", "warning",
     "pioneering / innovating"),
    ("a deep dive", "cliche_metaphor", "warning",
     "a detailed look / an in-depth analysis"),
    ("deep dive into", "cliche_metaphor", "warning",
     "examine / explore / analyze"),
    ("take a deep dive", "cliche_metaphor", "warning",
     "examine closely / explore"),
    ("level the playing field", "cliche_metaphor", "warning",
     "create equal opportunity"),
    ("disrupt", "booster_word", "warning",
     "change / challenge / shake up"),
    ("disruptive", "booster_word", "warning",
     "innovative / groundbreaking"),
    ("disruption", "booster_word", "warning",
     "change / innovation"),
    ("proactive", "overused_word", "info",
     "forward-looking / prepared"),
    ("scalable", "overused_word", "info",
     "expandable / flexible"),
    ("future-proof", "booster_word", "warning",
     "resilient / adaptable"),
    ("future-proofing", "booster_word", "warning",
     "preparing for the future"),
    ("end-to-end", "overused_word", "info",
     "complete / full"),
    ("all-encompassing", "overused_word", "warning",
     "complete / comprehensive"),
    ("world-class", "booster_word", "warning",
     "excellent / top-quality"),
    ("next-generation", "booster_word", "warning",
     "next / upcoming / future"),
    ("AI-powered", "booster_word", "info",
     "AI-driven / using AI"),
    ("AI-driven", "booster_word", "info",
     "using AI / powered by AI"),
    ("smart", "overused_word", "info",
     "intelligent / clever"),
    ("smart city", "overused_word", "info",
     "connected city / digital city"),
    ("smart solution", "overused_word", "info",
     "intelligent solution / digital solution"),
    ("digital transformation", "overused_word", "warning",
     "digitalization / going digital"),
    ("data-driven", "overused_word", "info",
     "based on data / informed by data"),
    ("actionable insights", "overused_word", "warning",
     "useful findings / practical advice"),
    ("leverage data", "cliche_phrase", "warning",
     "use data"),
    ("harness the power", "cliche_metaphor", "error",
     "use / take advantage of"),
    ("harness the potential", "cliche_metaphor", "error",
     "use / take advantage of"),
    ("unlock the potential", "cliche_metaphor", "warning",
     "realize the potential / use the potential"),
    ("tap into", "cliche_metaphor", "info",
     "access / use / connect with"),
    ("bring to the table", "cliche_metaphor", "warning",
     "contribute / offer / provide"),
    ("on the table", "cliche_metaphor", "info",
     "available / proposed"),
    ("piece of the puzzle", "cliche_metaphor", "warning",
     "part / element / factor"),
    ("big picture", "cliche_metaphor", "info",
     "overall situation / broader view"),
    ("bird's-eye view", "cliche_metaphor", "info",
     "overview / summary"),
    ("boils down to", "cliche_metaphor", "info",
     "comes down to / reduces to"),
    ("dive right in", "cliche_metaphor", "info",
     "start / begin"),
    ("let's dive in", "cliche_metaphor", "info",
     "Let's start / Let's begin"),
    ("let's get started", "cliche_phrase", "info",
     "Delete -- start directly"),
    ("without further ado", "cliche_phrase", "warning",
     "Delete entirely"),
    ("without further delay", "cliche_phrase", "warning",
     "Delete entirely"),
]


# ---------------------------------------------------------------------------
# Structural cliché patterns (regex-based)
# ---------------------------------------------------------------------------

STRUCTURAL_PATTERNS: List[Tuple[str, str, str, str]] = [
    # (regex pattern, category, severity, description)
    (r"(?i)^while\s+.+,\s+(it|this|that|we|they)\s+",
     "binary_contrast", "warning",
     "Binary contrast opener: 'While X, Y...' is a common AI structure"),
    (r"(?i)^although\s+.+,\s+(it|this|that|we|they)\s+",
     "binary_contrast", "warning",
     "Binary contrast opener: 'Although X, Y...' is a common AI structure"),
    (r"(?i)^despite\s+.+,\s+(it|this|that|we|they)\s+",
     "binary_contrast", "warning",
     "Binary contrast opener: 'Despite X, Y...' is a common AI structure"),
    (r"(?i)^--\s+[a-z]",  # dramatic dash opening
     "dramatic_opening", "warning",
     "Dramatic dash opening is a common AI narrative technique"),
    (r"(?i)not only.+but also",
     "not_only_but_also", "info",
     "'Not only... but also' is overused in AI text"),
    (r"(?i)both.+and\s+",
     "both_and", "info",
     "'Both... and' is frequently overused in AI text"),
    (r"(?i)from\s+.+\s+to\s+.+\s+to\s+",
     "triple_list", "info",
     "Triple-structure lists are common in AI-generated text"),
    (r"(?i)whether\s+it\s+['']?s?\s+.+\s+or\s+",
     "whether_or", "warning",
     "'Whether it's X or Y' is a common AI framing pattern"),
]


# ---------------------------------------------------------------------------
# Sentence-starting patterns (overused in AI text)
# ---------------------------------------------------------------------------

SENTENCE_STARTERS: List[Tuple[str, str, str]] = [
    # (starter word/phrase, category, severity)
    ("In today", "starter_in", "info"),
    ("In an", "starter_in", "info"),
    ("In the", "starter_in", "info"),
    ("In recent", "starter_in", "info"),
    ("As we", "starter_as", "info"),
    ("As the", "starter_as", "info"),
    ("As technology", "starter_as", "info"),
    ("As businesses", "starter_as", "info"),
    ("With the", "starter_with", "info"),
    ("With an", "starter_with", "info"),
    ("With more", "starter_with", "info"),
    ("The rapid", "starter_the", "info"),
    ("The growing", "starter_the", "info"),
    ("The increasing", "starter_the", "info"),
    ("The world", "starter_the", "info"),
    ("The rise", "starter_the", "info"),
    ("The importance", "starter_the", "info"),
    ("The need", "starter_the", "info"),
    ("The ability", "starter_the", "info"),
    ("The field", "starter_the", "info"),
    ("The concept", "starter_the", "info"),
    ("The role", "starter_the", "info"),
    ("The impact", "starter_the", "info"),
    ("The evolution", "starter_the", "info"),
    ("The intersection", "starter_the", "info"),
    ("The integration", "starter_the", "info"),
    ("The emergence", "starter_the", "info"),
    ("The proliferation", "starter_the", "info"),
    ("The adoption", "starter_the", "info"),
    ("The demand", "starter_the", "info"),
    ("The landscape", "starter_the", "info"),
    ("The future", "starter_the", "info"),
    ("The potential", "starter_the", "info"),
    ("The challenge", "starter_the", "info"),
    ("The solution", "starter_the", "info"),
    ("The key", "starter_the", "info"),
    ("The question", "starter_the", "info"),
    ("The answer", "starter_the", "info"),
    ("The truth", "starter_the", "info"),
    ("The fact", "starter_the", "info"),
    ("The reality", "starter_the", "info"),
    ("The beauty", "starter_the", "info"),
    ("The power", "starter_the", "info"),
    ("The value", "starter_the", "info"),
    ("The process", "starter_the", "info"),
    ("The approach", "starter_the", "info"),
    ("The strategy", "starter_the", "info"),
    ("The framework", "starter_the", "info"),
    ("The methodology", "starter_the", "info"),
    ("The platform", "starter_the", "info"),
    ("The technology", "starter_the", "info"),
    ("The industry", "starter_the", "info"),
    ("The market", "starter_the", "info"),
    ("The organization", "starter_the", "info"),
    ("The team", "starter_the", "info"),
    ("The individual", "starter_the", "info"),
    ("The user", "starter_the", "info"),
    ("The customer", "starter_the", "info"),
    ("The client", "starter_the", "info"),
    ("The reader", "starter_the", "info"),
    ("The audience", "starter_the", "info"),
    ("The community", "starter_the", "info"),
    ("The society", "starter_the", "info"),
    ("The global", "starter_the", "info"),
    ("The modern", "starter_the", "info"),
    ("The digital", "starter_the", "info"),
    ("The traditional", "starter_the", "info"),
    ("The conventional", "starter_the", "info"),
    ("The contemporary", "starter_the", "info"),
    ("The current", "starter_the", "info"),
    ("The ongoing", "starter_the", "info"),
    ("The ever-growing", "starter_the", "info"),
    ("The ever-increasing", "starter_the", "info"),
    ("The ever-evolving", "starter_the", "info"),
]


# ---------------------------------------------------------------------------
# Hedging patterns (excessive caution / uncertainty)
# ---------------------------------------------------------------------------

HEDGE_PATTERNS: List[Tuple[str, str, str]] = [
    # (pattern, category, severity)
    ("it could be argued that", "hedge", "warning"),
    ("some might say", "hedge", "info"),
    ("one could argue", "hedge", "info"),
    ("it seems that", "hedge", "info"),
    ("it appears that", "hedge", "info"),
    ("there is a possibility", "hedge", "info"),
    ("may potentially", "hedge", "warning"),
    ("could potentially", "hedge", "warning"),
    ("might potentially", "hedge", "warning"),
    ("it is possible that", "hedge", "info"),
    ("it is likely that", "hedge", "info"),
    ("to some extent", "hedge", "info"),
    ("in some cases", "hedge", "info"),
    ("in certain cases", "hedge", "info"),
    ("under certain circumstances", "hedge", "info"),
    ("arguably", "hedge", "info"),
    ("perhaps", "hedge", "info"),
    ("possibly", "hedge", "info"),
    ("to a certain degree", "hedge", "info"),
    ("more or less", "hedge", "info"),
    ("for the most part", "hedge", "info"),
    ("generally speaking", "hedge", "info"),
    ("broadly speaking", "hedge", "info"),
]


# ---------------------------------------------------------------------------
# Booster / hype words
# ---------------------------------------------------------------------------

BOOSTER_WORDS: List[Tuple[str, str, str]] = [
    # (word, category, severity)
    ("revolutionary", "booster", "error"),
    ("groundbreaking", "booster", "error"),
    ("game-changing", "booster", "error"),
    ("paradigm-shifting", "booster", "error"),
    ("unparalleled", "booster", "error"),
    ("extraordinary", "booster", "warning"),
    ("remarkable", "booster", "warning"),
    ("astonishing", "booster", "warning"),
    ("breathtaking", "booster", "warning"),
    ("phenomenal", "booster", "warning"),
    ("incredible", "booster", "warning"),
    ("amazing", "booster", "info"),
    ("stunning", "booster", "warning"),
    ("powerful", "booster", "info"),
    ("immensely", "booster", "warning"),
    ("vastly", "booster", "warning"),
    ("tremendously", "booster", "warning"),
    ("significantly", "booster", "info"),
    ("substantially", "booster", "info"),
    ("dramatically", "booster", "warning"),
    ("drastically", "booster", "warning"),
    ("exponentially", "booster", "warning"),
    ("fundamentally", "booster", "info"),
    ("essentially", "booster", "info"),
    ("absolutely", "booster", "info"),
    ("completely", "booster", "info"),
    ("totally", "booster", "info"),
    ("utterly", "booster", "warning"),
    ("thoroughly", "booster", "info"),
]


def get_all_rules() -> Dict[str, list]:
    """Return all English detection rules as a dictionary.

    Returns:
        Dict with keys: 'cliche_phrases', 'structural_patterns',
        'sentence_starters', 'hedge_patterns', 'booster_words'.
    """
    return {
        "cliche_phrases": CLICHE_PHRASES,
        "structural_patterns": STRUCTURAL_PATTERNS,
        "sentence_starters": SENTENCE_STARTERS,
        "hedge_patterns": HEDGE_PATTERNS,
        "booster_words": BOOSTER_WORDS,
    }
