"""Chinese AI text pattern rules.

This module defines AI-style phrases, structural patterns, and stylistic
markers commonly found in AI-generated Chinese text. Each rule has a
category, severity, and optional replacement suggestion.
"""

from typing import Dict, List, Tuple


# ---------------------------------------------------------------------------
# AI-style phrases -- exact or near-exact string matches
# ---------------------------------------------------------------------------

CLICHE_PHRASES: List[Tuple[str, str, str, str]] = [
    # (pattern, category, severity, replacement)
    ("随着...的不断发展", "cliche_opening", "error",
     "直接切入主题，删除套话"),
    ("随着社会的不断发展", "cliche_opening", "error",
     "直接切入主题"),
    ("随着科技的不断进步", "cliche_opening", "error",
     "直接切入主题"),
    ("随着互联网的快速发展", "cliche_opening", "error",
     "直接切入主题"),
    ("随着人工智能的快速发展", "cliche_opening", "error",
     "直接切入主题"),
    ("随着数字化的深入推进", "cliche_opening", "error",
     "直接切入主题"),
    ("随着信息技术的飞速发展", "cliche_opening", "error",
     "直接切入主题"),
    ("在当今快速变化的时代", "cliche_opening", "error",
     "直接切入主题"),
    ("在当今社会", "cliche_opening", "warning",
     "直接切入主题"),
    ("在当今世界", "cliche_opening", "warning",
     "直接切入主题"),
    ("在当今时代", "cliche_opening", "warning",
     "直接切入主题"),
    ("在数字化浪潮中", "cliche_opening", "warning",
     "直接切入主题"),
    ("在这个信息爆炸的时代", "cliche_opening", "error",
     "直接切入主题"),
    ("值得注意的是", "filler_hedge", "warning",
     "删除，直接陈述要点"),
    ("需要指出的是", "filler_hedge", "warning",
     "删除，直接陈述要点"),
    ("需要强调的是", "filler_hedge", "warning",
     "删除，直接陈述要点"),
    ("不得不说", "filler_hedge", "info",
     "删除"),
    ("众所周知", "filler_hedge", "warning",
     "删除"),
    ("毋庸置疑", "filler_hedge", "warning",
     "删除"),
    ("综上所述", "cliche_closing", "warning",
     "删除，让结论自己说话"),
    ("总而言之", "cliche_closing", "warning",
     "删除"),
    ("总的来说", "cliche_closing", "info",
     "删除"),
    ("简而言之", "cliche_closing", "info",
     "删除"),
    ("由此可见", "cliche_closing", "info",
     "删除"),
    ("深入探讨", "overused_word", "warning",
     "探讨 / 分析 / 研究"),
    ("全面解析", "overused_word", "warning",
     "分析 / 解读"),
    ("全面解读", "overused_word", "warning",
     "解读 / 分析"),
    ("深度解析", "overused_word", "warning",
     "解析 / 分析"),
    ("深度解读", "overused_word", "warning",
     "解读 / 分析"),
    ("赋能", "overused_word", "error",
     "帮助 / 支持 / 推动"),
    ("助力", "overused_word", "warning",
     "帮助 / 推动 / 促进"),
    ("打造", "overused_word", "info",
     "建设 / 创建 / 做"),
    ("引领", "overused_word", "warning",
     "带领 / 推动 / 促进"),
    ("全方位", "overused_word", "warning",
     "全面 / 多方面"),
    ("一站式", "overused_word", "warning",
     "综合 / 一体化"),
    ("深度融合", "overused_word", "warning",
     "深度结合 / 融合"),
    ("深度融合", "overused_word", "warning",
     "结合 / 融合"),
    ("协同发展", "overused_word", "warning",
     "共同发展 / 协作发展"),
    ("高质量发展", "overused_word", "info",
     "质量发展 / 优质发展"),
    ("可持续发展", "overused_word", "info",
     "长期发展 / 持续发展"),
    ("创新发展", "overused_word", "info",
     "创新发展 / 创新推动"),
    ("转型升级", "overused_word", "warning",
     "转型 / 升级"),
    ("优化升级", "overused_word", "info",
     "优化 / 改进"),
    ("迭代升级", "overused_word", "info",
     "迭代 / 更新"),
    ("降本增效", "overused_word", "warning",
     "降低成本、提高效率"),
    ("提质增效", "overused_word", "warning",
     "提高质量、增加效率"),
    ("开源节流", "overused_word", "info",
     "节省开支"),
    ("多措并举", "overused_word", "warning",
     "多种措施"),
    ("统筹推进", "overused_word", "warning",
     "推进 / 推动"),
    ("扎实推进", "overused_word", "info",
     "推进 / 推动"),
    ("稳步推进", "overused_word", "info",
     "推进"),
    ("积极推进", "overused_word", "info",
     "推进"),
    ("大力推进", "overused_word", "info",
     "推进"),
    ("加快推进", "overused_word", "info",
     "加快"),
    ("落地生根", "cliche_metaphor", "error",
     "落实 / 实施"),
    ("落地见效", "cliche_metaphor", "warning",
     "见效 / 产生效果"),
    ("落地实施", "cliche_metaphor", "info",
     "实施 / 执行"),
    ("开花结果", "cliche_metaphor", "error",
     "取得成果 / 见效"),
    ("硕果累累", "cliche_metaphor", "error",
     "成果丰硕 / 成绩显著"),
    ("蓬勃发展", "cliche_metaphor", "warning",
     "快速发展 / 迅速发展"),
    ("方兴未艾", "cliche_metaphor", "warning",
     "正在发展 / 兴起"),
    ("如火如荼", "cliche_metaphor", "warning",
     "正在热烈进行"),
    ("蔚然成风", "cliche_metaphor", "warning",
     "形成风气 / 成为趋势"),
    ("势不可挡", "cliche_metaphor", "warning",
     "势头强劲"),
    ("异军突起", "cliche_metaphor", "warning",
     "迅速崛起"),
    ("独树一帜", "cliche_metaphor", "info",
     "独具特色 / 与众不同"),
    ("举足轻重", "cliche_metaphor", "info",
     "重要 / 关键"),
    ("不可或缺", "cliche_metaphor", "info",
     "必要 / 重要"),
    ("至关重要", "cliche_metaphor", "warning",
     "非常重要 / 关键"),
    ("息息相关", "cliche_metaphor", "info",
     "密切相关 / 有关"),
    ("密不可分", "cliche_metaphor", "info",
     "紧密相关"),
    ("相辅相成", "cliche_metaphor", "info",
     "互相促进 / 互补"),
    ("齐头并进", "cliche_metaphor", "info",
     "共同发展 / 并行发展"),
    ("携手共进", "cliche_metaphor", "warning",
     "合作 / 共同努力"),
    ("砥砺前行", "cliche_metaphor", "error",
     "努力前进 / 继续努力"),
    ("乘风破浪", "cliche_metaphor", "error",
     "克服困难 / 奋勇前进"),
    ("勇立潮头", "cliche_metaphor", "error",
     "引领 / 领先"),
    ("抢占先机", "cliche_metaphor", "warning",
     "抓住机会"),
    ("未雨绸缪", "cliche_metaphor", "info",
     "提前准备 / 预做准备"),
    ("厚积薄发", "cliche_metaphor", "info",
     "积累后爆发 / 长期积累"),
    ("破茧成蝶", "cliche_metaphor", "error",
     "蜕变 / 转变"),
    ("凤凰涅槃", "cliche_metaphor", "error",
     "重生 / 蜕变"),
    ("脱胎换骨", "cliche_metaphor", "warning",
     "彻底改变"),
    ("焕然一新", "cliche_metaphor", "info",
     "全新面貌 / 完全改变"),
    ("日新月异", "cliche_metaphor", "info",
     "快速变化"),
    ("突飞猛进", "cliche_metaphor", "info",
     "快速进步 / 迅速发展"),
    ("蒸蒸日上", "cliche_metaphor", "info",
     "越来越好 / 不断发展"),
    ("欣欣向荣", "cliche_metaphor", "info",
     "繁荣发展"),
    ("百尺竿头", "cliche_metaphor", "warning",
     "更进一步"),
    ("更上一层楼", "cliche_metaphor", "warning",
     "更进一步"),
    ("前所未有", "booster_word", "warning",
     "罕见 / 罕见程度"),
    ("史无前例", "booster_word", "warning",
     "前所未有 / 空前"),
    ("举世瞩目", "booster_word", "warning",
     "引人注目 / 受到关注"),
    ("享誉中外", "booster_word", "warning",
     "知名 / 著名"),
    ("首屈一指", "booster_word", "warning",
     "领先 / 第一"),
    ("遥遥领先", "booster_word", "error",
     "领先 / 领先一步"),
    ("独占鳌头", "booster_word", "warning",
     "领先 / 第一"),
    ("无可比拟", "booster_word", "warning",
     "无法相比 / 独特"),
    ("得天独厚", "booster_word", "info",
     "条件优越"),
    ("不可或缺", "booster_word", "info",
     "必要 / 必不可少"),
    ("至关重要", "booster_word", "warning",
     "非常重要"),
    ("至关重要", "booster_word", "warning",
     "非常重要 / 关键"),
    ("核心驱动力", "overused_word", "warning",
     "主要动力 / 关键因素"),
    ("关键引擎", "overused_word", "warning",
     "关键因素 / 主要推动力"),
    ("重要抓手", "overused_word", "warning",
     "重要手段 / 关键方法"),
    ("有力支撑", "overused_word", "info",
     "有力支持 / 支撑"),
    ("坚实保障", "overused_word", "info",
     "可靠保障"),
    ("坚实基础", "overused_word", "info",
     "扎实基础"),
    ("重要载体", "overused_word", "info",
     "重要平台 / 主要媒介"),
    ("有效途径", "overused_word", "info",
     "有效方法 / 可行方式"),
    ("关键环节", "overused_word", "info",
     "重要环节 / 关键部分"),
    ("重要组成部分", "wordiness", "warning",
     "重要部分"),
    ("不可或缺的一部分", "wordiness", "warning",
     "必要部分 / 重要部分"),
    ("发挥着重要作用", "wordiness", "warning",
     "很重要 / 起重要作用"),
    ("扮演着重要角色", "wordiness", "warning",
     "很重要 / 起重要作用"),
    ("具有重要意义", "wordiness", "info",
     "很重要 / 有意义"),
    ("具有深远影响", "wordiness", "info",
     "影响深远"),
    ("具有重大意义", "wordiness", "info",
     "意义重大"),
    ("具有重要的现实意义", "wordiness", "warning",
     "很有现实意义"),
    ("具有重要的理论和实践意义", "wordiness", "warning",
     "理论和实践意义都很大"),
    ("不仅...而且", "structural_cliche", "info",
     "直接陈述，避免模板化"),
    ("一方面...另一方面", "structural_cliche", "info",
     "简化表达"),
    ("既...又", "structural_cliche", "info",
     "简化表达"),
    ("无论...都", "structural_cliche", "info",
     "简化表达"),
    ("不仅...还", "structural_cliche", "info",
     "简化表达"),
    ("首先...其次...最后", "structural_cliche", "info",
     "使用更自然的过渡"),
    ("第一...第二...第三", "structural_cliche", "info",
     "使用更自然的过渡"),
    ("一是...二是...三是", "structural_cliche", "info",
     "使用更自然的过渡"),
    ("为广大...提供", "overused_word", "info",
     "为...提供"),
    ("致力于", "overused_word", "info",
     "努力 / 专注于"),
    ("秉承", "overused_word", "info",
     "坚持 / 遵循"),
    ("践行", "overused_word", "info",
     "实践 / 执行"),
    ("贯彻", "overused_word", "info",
     "落实 / 执行"),
    ("落实", "overused_word", "info",
     "实施 / 执行"),
    ("聚焦", "overused_word", "info",
     "关注 / 集中于"),
    ("围绕", "overused_word", "info",
     "以...为中心"),
    ("依托", "overused_word", "info",
     "依靠 / 基于"),
    ("基于", "overused_word", "info",
     "以...为基础"),
    ("以...为导向", "overused_word", "info",
     "导向为..."),
    ("以...为核心", "overused_word", "info",
     "核心是..."),
    ("以...为抓手", "overused_word", "warning",
     "以...为重点 / 以...为关键"),
    ("以...为引领", "overused_word", "warning",
     "以...为主导"),
    ("以...为驱动", "overused_word", "warning",
     "以...推动"),
    ("以...为基础", "overused_word", "info",
     "基于..."),
    ("打通...最后一公里", "cliche_metaphor", "error",
     "解决最后的问题 / 完成最后一步"),
    ("补齐短板", "cliche_metaphor", "info",
     "弥补不足"),
    ("拉长长板", "cliche_metaphor", "info",
     "发挥优势"),
    ("弯道超车", "cliche_metaphor", "warning",
     "后来居上 / 超越"),
    ("换道超车", "cliche_metaphor", "warning",
     "另辟蹊径 / 转型超越"),
    ("顶层设计", "overused_word", "warning",
     "整体规划 / 总体设计"),
    ("底层逻辑", "overused_word", "warning",
     "基本原理 / 核心逻辑"),
    ("闭环", "overused_word", "warning",
     "完整流程 / 循环"),
    ("颗粒度", "overused_word", "warning",
     "精细程度 / 详细程度"),
    ("对齐", "overused_word", "warning",
     "统一 / 协调"),
    ("拉通", "overused_word", "warning",
     "打通 / 连通"),
    ("复盘", "overused_word", "info",
     "回顾 / 总结"),
    ("沉淀", "overused_word", "info",
     "积累 / 总结"),
    ("心智", "overused_word", "info",
     "认知 / 思维"),
    ("心智模型", "overused_word", "info",
     "思维模型 / 认知框架"),
    ("底层架构", "overused_word", "info",
     "基础架构 / 基本结构"),
    ("生态体系", "overused_word", "warning",
     "生态系统 / 体系"),
    ("全链路", "overused_word", "warning",
     "全流程 / 全链条"),
    ("全场景", "overused_word", "warning",
     "全场景 / 所有场景"),
    ("全生命周期", "overused_word", "warning",
     "完整周期 / 全周期"),
    ("全渠道", "overused_word", "info",
     "多渠道 / 各渠道"),
    ("全矩阵", "overused_word", "warning",
     "多平台 / 全平台"),
    ("多维度", "overused_word", "info",
     "多方面 / 多角度"),
    ("多层次的", "overused_word", "info",
     "多层 / 多级"),
    ("体系化", "overused_word", "info",
     "系统化 / 成体系"),
    ("系统化", "overused_word", "info",
     "系统 / 有系统"),
    ("规范化", "overused_word", "info",
     "规范 / 标准化"),
    ("标准化", "overused_word", "info",
     "标准 / 统一标准"),
    ("精细化", "overused_word", "info",
     "精细 / 精确"),
    ("智能化", "overused_word", "info",
     "智能 / 自动化"),
    ("数字化", "overused_word", "info",
     "数字 / 信息"),
    ("智慧化", "overused_word", "info",
     "智能 / 智慧"),
    ("网格化", "overused_word", "info",
     "网格 / 分区管理"),
    ("链条化", "overused_word", "info",
     "链条 / 链式"),
    ("矩阵化", "overused_word", "info",
     "矩阵 / 矩阵式"),
    ("平台化", "overused_word", "info",
     "平台 / 平台式"),
    ("中台化", "overused_word", "info",
     "中台 / 中台式"),
    ("一体化", "overused_word", "info",
     "统一 / 整合"),
    ("多元化", "overused_word", "info",
     "多样 / 多元"),
    ("个性化", "overused_word", "info",
     "个人化 / 定制"),
    ("定制化", "overused_word", "info",
     "定制 / 量身定制"),
    ("场景化", "overused_word", "info",
     "基于场景 / 场景驱动"),
    ("数据驱动", "overused_word", "info",
     "以数据为基础 / 数据导向"),
    ("技术驱动", "overused_word", "info",
     "以技术为基础 / 技术导向"),
    ("创新驱动", "overused_word", "info",
     "以创新为基础 / 创新导向"),
    ("结果导向", "overused_word", "info",
     "以结果为基础"),
    ("用户导向", "overused_word", "info",
     "以用户为中心"),
    ("市场导向", "overused_word", "info",
     "以市场为中心"),
]


# ---------------------------------------------------------------------------
# Structural patterns (regex-based)
# ---------------------------------------------------------------------------

STRUCTURAL_PATTERNS: List[Tuple[str, str, str, str]] = [
    # (regex pattern, category, severity, description)
    (r"随着.+?的(?:不断|持续|快速|飞速|迅猛|日益|逐步)(?:发展|进步|变化|演变|提升)",
     "cliche_opening", "error",
     "AI风格开头：'随着...的不断发展' 是典型AI套话"),
    (r"在(?:当今|当前|今天|如今|眼下)(?:的)?(?:快速|瞬息万变|日新月异)?(?:变化|发展)?(?:的)?(?:时代|社会|世界|环境)",
     "cliche_opening", "error",
     "AI风格开头：'在当今...' 是典型AI套话"),
    (r"^(?:首先|第一|一是)[，,]?\s*(?:其次|第二|二是)[，,]?\s*(?:最后|第三|三是)",
     "enumeration_structure", "info",
     "模板化列举结构：首先...其次...最后"),
    (r"不仅.+?而且.+?更",
     "triple_climax", "warning",
     "三重递进结构：不仅...而且...更"),
    (r"无论是.+?还是.+?都",
     "whether_or", "info",
     "AI常用框架：'无论是...还是...都'"),
]


# ---------------------------------------------------------------------------
# Sentence-starting patterns
# ---------------------------------------------------------------------------

SENTENCE_STARTERS: List[Tuple[str, str, str]] = [
    # (starter, category, severity)
    ("随着", "starter_with", "info"),
    ("在当今", "starter_in", "info"),
    ("在当前", "starter_in", "info"),
    ("在如今", "starter_in", "info"),
    ("近年来", "starter_recent", "info"),
    ("近年来", "starter_recent", "info"),
    ("当前", "starter_current", "info"),
    ("目前", "starter_current", "info"),
    ("现如今", "starter_current", "info"),
    ("不可否认", "starter_hedge", "warning"),
    ("毋庸置疑", "starter_hedge", "warning"),
    ("众所周知", "starter_hedge", "warning"),
    ("值得注意的是", "starter_hedge", "warning"),
    ("需要指出的是", "starter_hedge", "warning"),
    ("从某种意义上说", "starter_hedge", "info"),
    ("从一定程度上", "starter_hedge", "info"),
    ("总体来看", "starter_summary", "info"),
    ("总体而言", "starter_summary", "info"),
    ("从整体来看", "starter_summary", "info"),
    ("从宏观来看", "starter_summary", "info"),
]


# ---------------------------------------------------------------------------
# Hedging patterns
# ---------------------------------------------------------------------------

HEDGE_PATTERNS: List[Tuple[str, str, str]] = [
    # (pattern, category, severity)
    ("在一定程度上", "hedge", "info"),
    ("在某种程度上", "hedge", "info"),
    ("从某种程度上", "hedge", "info"),
    ("从某种意义上", "hedge", "info"),
    ("可以说", "hedge", "info"),
    ("似乎", "hedge", "info"),
    ("可能", "hedge", "info"),
    ("或许", "hedge", "info"),
    ("大概", "hedge", "info"),
    ("也许", "hedge", "info"),
    ("在一定程度上来说", "hedge", "warning"),
    ("从某种意义上来说", "hedge", "warning"),
]


# ---------------------------------------------------------------------------
# Booster / hype words
# ---------------------------------------------------------------------------

BOOSTER_WORDS: List[Tuple[str, str, str]] = [
    # (word, category, severity)
    ("颠覆性", "booster", "error"),
    ("革命性", "booster", "error"),
    ("划时代", "booster", "error"),
    ("前所未有", "booster", "warning"),
    ("史无前例", "booster", "warning"),
    ("举世瞩目", "booster", "warning"),
    ("遥遥领先", "booster", "error"),
    ("独占鳌头", "booster", "warning"),
    ("无可比拟", "booster", "warning"),
    ("空前绝后", "booster", "error"),
    ("绝无仅有", "booster", "warning"),
    ("登峰造极", "booster", "warning"),
    ("叹为观止", "booster", "warning"),
    ("震撼人心", "booster", "warning"),
    ("意义深远", "booster", "info"),
    ("影响深远", "booster", "info"),
    ("极为", "booster", "info"),
    ("极其", "booster", "info"),
    ("非常", "booster", "info"),
    ("十分", "booster", "info"),
    ("格外", "booster", "info"),
    ("尤其", "booster", "info"),
    ("特别", "booster", "info"),
]


def get_all_rules() -> Dict[str, list]:
    """Return all Chinese detection rules as a dictionary.

    Returns:
        Dict with keys: 'cliche_phrases', 'structural_patterns',
        'sentence_starters', 'hedge_patterns', 'booster_words'.
    """
    return {
        "cliche_phrases": CLICHE_PHRASES,
        "structural_patterns": STRUCTURAL_PATTERNS,
        "sentence_starters": SENTENCE_STARTERS,
        "hedge_patterns": HEDGE_PATTERNS,
        "booster_words": BOOSTER_WORDS,
    }
